export const ActionsTypes = {
  PIX_CASH_IN: 'PIX_CASH_IN',
  PIX_CASH_OUT: 'PIX_CASH_OUT',
  ADD_CREDIT: 'ADD_CREDIT',
  REMOVE_CREDIT: 'WITHDRAW_CREDIT',
  PLACE_BET: 'PLACE_BET',
  WIN_BET: 'WIN_BET',
}
